(function(){var a=document.URL+"";if("dantri.com.vn"==document.domain+"")try{window._ADM_Channel="/"+/dantri.com.vn\/([a-zA-Z\+\-]+)/.exec(a)[1]+"/"}catch(b){}})();
"undefined"==typeof AMCDNCheckSend&&(window.AMCDNCheckSend="send",function(){function a(a){return 0<document.cookie.length&&(c_start=document.cookie.indexOf(a+"="),-1!=c_start)?(c_start=c_start+a.length+1,c_end=document.cookie.indexOf(";",c_start),-1==c_end&&(c_end=document.cookie.length),unescape(document.cookie.substring(c_start,c_end))):""}function b(a,b,c,e,d,f){(new Date).getTime();e=""==e?"/":e;c=0==c||""==c?(new Date(+new Date+864E5)).toGMTString():(new Date(+new Date+6E4*c)).toGMTString();
a=[a+"="+escape(b)];for(var h in c={expires:c,path:e,domain:d})c[h]&&a.push(h+"="+c[h]);return f&&a.push("secure"),document.cookie=a.join(";"),!0}"undefined"==typeof window.__admloadPageId&&(window.__admloadPageId=function(){function a(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}return a()+a()+a()+a()+a()+a()+a()+a()}());window._admislocalStorage=function(){try{if(!("localStorage"in window&&null!==window.localStorage))return!1;try{localStorage.setItem("_admstorage",""),
localStorage.removeItem("_admstorage")}catch(h){return!1}return!0}catch(h){return!1}}();window._admislocalStorage?(window.__admloadPageIdc=localStorage.__uidac,window.__admloadPageIdc||(localStorage.__uidac=__admloadPageId,window.__admloadPageIdc=__admloadPageId)):(window.__admloadPageIdc=a("__uidac"),""==window.__admloadPageIdc&&b("__uidac",__admloadPageId,5E6,"/","."+document.domain));var c=a("__uif");c=/__uid:([0-9]+)/.exec(c);var e="";c&&2<=c.length&&(e=encodeURIComponent(c[1]));var d="https:"==
document.location.protocol?"https:":"http:";c=new Image;var f=document.location.hostname;d=d+"//amcdn.vn/ftest?lsn="+window.__admloadPageId+"&dg="+window.__admloadPageIdc+"&ui="+e+"&url="+encodeURIComponent("http://1"+f+document.location.pathname)+"&rd="+Math.random();c.src=d;c=new Image;c.onerror=function(){(new Image).src=("https:"==document.location.protocol?"https:":"http:")+"//amcdn.vn/blc?lsn="+window.__admloadPageId+"&dg="+window.__admloadPageIdc+"&ui="+e+"&url="+encodeURIComponent("http://errorlg1"+
f+document.location.pathname)+"&rd="+Math.random()};c.src=("https:"==document.location.protocol?"https:":"http:")+"//lg1.logging.admicro.vn/ftest?lsn="+window.__admloadPageId+"&dg="+window.__admloadPageIdc+"&ui="+e+"&url="+encodeURIComponent("http://2"+f+document.location.pathname)+"&rd="+Math.random();(function(a){var b=!1,c=document.createElement("script");document.getElementsByTagName("head")[0].appendChild(c);var d=function(){if(!b){(new Image).src=("https:"==document.location.protocol?"https:":
"http:")+"//amcdn.vn/blc?lsn="+window.__admloadPageId+"&url="+encodeURIComponent(document.URL)+"&dg="+window.__admloadPageIdc+"&ui="+e;var a=!1,c=function(){"undefined"===typeof ADM_TrackingSend||a?window.setTimeout(function(){c()},500):(a=!0,(new Image).src=("https:"==document.location.protocol?"https:":"http:")+"//amcdn.vn/blc?dg="+window.__admloadPageIdc+"&ui="+e+"&url="+encodeURIComponent("http://blockpartern"+f+document.location.pathname)+"&rd="+Math.random())};c();b=!0}};try{c.onerror=function(a){b||
d()},c.onabort=function(a){b||d()},c.oncancel=function(a){b||d()}}catch(n){}try{c.src=a}catch(n){}})("https://media1.admicro.vn/ads_codes/ads_code_1.ads")}());
try{var _admloadJs1=function(a,b){var c=document.createElement("script");c.type="text/javascript";c.src=a;2<=arguments.length&&(c.onload=b,c.onreadystatechange=function(){4!=c.readyState&&"complete"!=c.readyState||b()});document.getElementsByTagName("head")[0].appendChild(c)},ADM_TrackingSend$3=function(){try{window.admTrackingParam.url=window.admTrackingParam.url||document.URL}catch(e){}if("undefined"!=typeof __ADM_TrackingSend&&!0===__ADM_TrackingSend)return!1;ADM_AdsTracking.checkBrowser();var a=
"",b=0;window._AdmGetGa=function(){return""};window._AdmGetGa=function(){var a="";try{var b=window.performance||window.webkitPerformance;if(b=b&&b.timing){var c=b.navigationStart;a=";"+[b.loadEventStart-c,b.domainLookupEnd-b.domainLookupStart,b.connectEnd-b.connectStart,b.responseStart-b.requestStart,b.responseEnd-b.responseStart,b.fetchStart-c,b.domInteractive-c,b.domContentLoadedEventStart-c].join(";")}return";"+ADM_AdsTracking.getCookie("_ga")+a}catch(h){}return""};a="//lg1.logging.admicro.vn/_tracking1.gif?dg="+
__admloadPageIdc;a+="&fl="+paramBrowser.flashVersion();a+="&je="+paramBrowser.javaEnabled;a+="&sr="+paramBrowser.screen_Resolution;a+="&sc="+paramBrowser.screen_Color;a+="&hn="+paramBrowser.hostname;a+="&p="+paramBrowser.zenURL.encode(paramBrowser.url());a+="&r="+(""==paramBrowser.referrer?"":paramBrowser.zenURL.encode(paramBrowser.referrer));a="undefined"!=typeof _Analytics_Channel&&""!=_Analytics_Channel?a+("&cat="+encodeURIComponent(decodeURIComponent(_Analytics_Channel))):"undefined"!=typeof _ADM_Channel&&
""!=_ADM_Channel?a+("&cat="+encodeURIComponent(decodeURIComponent(_ADM_Channel))):a+"&cat=";try{var c=window.self!==window.top}catch(e){c=!0}c=c?1:0;-1!=paramBrowser.hostname.indexOf("enbac.com")&&(b=""!=ADM_AdsTracking.getCookie("province_id")?ADM_AdsTracking.getCookie("province_id"):0);-1!=paramBrowser.hostname.indexOf("rongbay.com")&&(b=""!=ADM_AdsTracking.getCookie("cityid")?ADM_AdsTracking.getCookie("cityid"):0);-1!=paramBrowser.hostname.indexOf("muachung.vn")&&(b=""!=ADM_AdsTracking.getCookie("muachung_cityMC")?
ADM_AdsTracking.getCookie("muachung_cityMC"):0);window.__ifr=c;window.__ADM_TrackingSend=!0;window.__ADMScrollcounter=0;window.__ADMScrollEnd=0;window.__ADMTrackingSendUrl=a+("&g="+b);window.__ADMTouch=0;window.__ADMMouse=0;window.__ADMisActive=0;window.__ADMTimeTk=Math.floor((new Date).getTime()/1E3);try{__ADMwdVis()&&(window.__ADMisActive=1)}catch(e){}ADMTrackingsend("s");ADMTrackingsend("v");"undefined"==typeof window.admTrackingParam.ispopup&&(admaddEventListener(window,"scroll",function(){window.__ADMScrollcounter+=
1;0>wPrototype.bdHeight()-(wPrototype.scrollTop()+wPrototype.wdHeight()+100)&&(window.__ADMScrollEnd=1)}),admaddEventListener(window,"blur",function(){__ADMisActive=0}),admaddEventListener(window,"focus",function(){__ADMisActive=1}),"ontouchstart"in window&&admaddEventListener(document,"touchmove",function(a){__ADMTouch++}),admaddEventListener(document,"mousemove",function(a){__ADMMouse++}),window.setTimeout(function(){var a,b="",c={hidden:"visibilitychange",webkitHidden:"webkitvisibilitychange",
mozHidden:"mozvisibilitychange",msHidden:"msvisibilitychange"};for(a in c)if(a in document){var h=c[a];b=a;break}document.addEventListener(h,function(){__ADMisActive=document[b]?0:1;ADMTrackingsend("p")})},5E3),chkadmTrackingt=window.setTimeout(function(){ADM_TrackingSendChk()},2E4),"beforeunload"in window||"onbeforeunload"in window)&&(-1!=navigator.userAgent.indexOf("Firefox")?admaddEventListener(window,"unload",function(){ADMTrackingsend("e")}):admaddEventListener(window,"beforeunload",function(){ADMTrackingsend("e")}))},
ADMTrackingsend=function(a){try{if(-1!=(document.domain+"").indexOf("vib.com.vn")&&"p"==a)return!1}catch(h){}window._AdmGetGa=function(){var a="";try{var b=window.performance||window.webkitPerformance;if(b=b&&b.timing){var c=b.navigationStart;a=";"+[b.loadEventStart-c,b.domainLookupEnd-b.domainLookupStart,b.connectEnd-b.connectStart,b.responseStart-b.requestStart,b.responseEnd-b.responseStart,b.fetchStart-c,b.domInteractive-c,b.domContentLoadedEventStart-c].join(";")}return";"+ADM_AdsTracking.getCookie("_ga")+
a}catch(m){}return""};if("undefined"==typeof window.__ADMTrackingSendUrl){var b="";b=("https:"==document.location.protocol?"https:":"http:")+"//lg1.logging.admicro.vn/_tracking1.gif?dg="+__admloadPageIdc;b+="&fl="+paramBrowser.flashVersion();b+="&je="+paramBrowser.javaEnabled;b+="&sr="+paramBrowser.screen_Resolution;b+="&sc="+paramBrowser.screen_Color;b+="&hn="+paramBrowser.hostname;b+="&p="+paramBrowser.zenURL.encode(paramBrowser.url());b+="&r="+(""==paramBrowser.referrer?"":paramBrowser.zenURL.encode(paramBrowser.referrer));
b="undefined"!=typeof _Analytics_Channel&&""!=_Analytics_Channel?b+("&cat="+encodeURIComponent(decodeURIComponent(_Analytics_Channel))):"undefined"!=typeof _ADM_Channel&&""!=_ADM_Channel?b+("&cat="+encodeURIComponent(decodeURIComponent(_ADM_Channel))):b+"&cat=";-1!=paramBrowser.hostname.indexOf("enbac.com")&&(g=""!=ADM_AdsTracking.getCookie("province_id")?ADM_AdsTracking.getCookie("province_id"):0);-1!=paramBrowser.hostname.indexOf("rongbay.com")&&(g=""!=ADM_AdsTracking.getCookie("cityid")?ADM_AdsTracking.getCookie("cityid"):
0);-1!=paramBrowser.hostname.indexOf("muachung.vn")&&(g=""!=ADM_AdsTracking.getCookie("muachung_cityMC")?ADM_AdsTracking.getCookie("muachung_cityMC"):0);b+="&g="+g;window.__ADMTrackingSendUrl=b}b=window.__ADMTrackingSendUrl+logposurlview+"&i="+encodeURIComponent(a+";"+__admPageloadid+";"+window.__ADMScrollcounter+";"+window.__ADMScrollEnd+";"+__ADMisActive+";"+__ADMMouse+";"+__ADMTouch+";"+(wPrototype.wdWidth()+"x"+wPrototype.wdHeight())+";"+window.__ifr+";"+("undefined"==typeof ADS_CHECKER?0:1)+
";"+__admloadPageId+";"+__admloadPageIdc+_AdmGetGa())+"&rdm="+Math.random();var c=navigator.userAgent+"",e=!1;if("s"==a){try{if(-1!=c.indexOf("Macintosh")||-1!=c.indexOf("Windows"))e=!0}catch(h){}if(!0===e){var d=document.createElement("iframe");d.src=b+ADM_AdsTracking.getParam();d.style.width="12px";d.style.height="12px";d.style.visibility="hidden";d.style.position="absolute";d.style.left="0px";d.style.bottom="0px";d.style.border="none";d.target="admTrackmain";d.name="admIframeTracking";d.id="admIframeTracking";
AdmonDomReady(function(){try{var a=document.createElement("div");a.style.position="absolute";a.style.bottom="0";a.style.left="0";a.style.width="1px";a.style.height="1px";a.style.overflow="hidden";a.style.visibility="hidden";document.body.appendChild(a);a.appendChild(d)}catch(l){}});a=function(a){if(-1!=a.origin.indexOf("logging.admicro.vn")&&(a=a.data,"object"==typeof a))try{"__CRT"==a[0]&&(a[0]="__create"),"__UF"==a[0]&&(a[0]="__ui"),"__C"!=a[0]&&ADM_AdsTracking.check(a[0],a[1],"","/")}catch(l){}};
window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent("onmessage",a,!1)}else d=document.createElement("script"),d.type="text/javascript",d.async=!0,d.src=b,a=document.getElementsByTagName("script")[0],a.parentNode.insertBefore(d,a)}else{var f=new Image;f.src=b+ADM_AdsTracking.getParam();"v"==a&&(f.onerror=function(){try{(new Image).src=(f.src+"").replace("lg1.logging.admicro.vn","amcdn.vn")}catch(h){}})}},ADM_TrackingSendChk=function(){__ADMisActive=__ADMwdVis()?1:0;var a=
Math.floor((new Date).getTime()/1E3);if(1==__ADMisActive||120<=a-__ADMTimeTk)__ADMTimeTk=a,ADMTrackingsend("p");chkadmTrackingt=999>_admBrV?window.setTimeout(function(){ADM_TrackingSendChk()},2E4):window.setTimeout(function(){ADM_TrackingSendChk()},6E4)},admRemoveEventListener=function(a,b,c){"removeEventListener"in a?a.removeEventListener(b,c):"detachEvent "in a&&a.detachEvent("on"+b,c)},admaddEventListener=function(a,b,c){"addEventListener"in a?a.addEventListener(b,c):"attachEvent"in a&&a.attachEvent("on"+
b,c)};if("undefined"==typeof logposurlview)var logposurlview="";if("undefined"==typeof chkadmTrackingt)var chkadmTrackingt;if("undefined"==typeof __admPageloadid)var __admPageloadid=(new Date).getTime();(function(){var a=!1,b=[];if(!window.AdmonDomReady||"function"!=typeof window.AdmonDomReady){var c=function(){if(!document.body)return setTimeout(c,13);for(var a=0;a<b.length;a++)b[a]();b=[]};window.AdmonDomReady=function(e){b.push(e);if("complete"==document.readyState)c();else if(!a){if(document.addEventListener){var d=
function(){document.removeEventListener("DOMContentLoaded",d,!1);c()};document.addEventListener("DOMContentLoaded",d,!1);window.addEventListener("load",c,!1)}else if(document.attachEvent){var f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),c())};document.attachEvent("onreadystatechange",f);window.attachEvent("onload",c);e=!1;try{e=null==window.frameElement}catch(l){}if(document.documentElement.doScroll&&e){var h=function(){if(0!=b.length){try{document.documentElement.doScroll("left")}catch(l){setTimeout(h,
1);return}c()}};h()}}a=!0}}}})();if(void 0===ADM_AdsTracking)var ADM_AdsTracking={version:"1.0.0",paramFlash:{},getFlashMovie:function(a){return-1!=navigator.appName.indexOf("Microsoft")?document.getElementById(a):document[a]},checkBrowser:function(){var a=!1;var b=navigator.appName;var c=navigator.userAgent+"",e,d=c.match(/(opera|chrome|safari|firefox|msie)\/?\s*(\.?\d+(\.\d+)*)/i);null==d&&-1==c.indexOf("MSIE")&&-1!=c.indexOf("Trident/")?(b=-1,null!=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/.exec(c)&&
(b=RegExp.$1),d=["MSIE",b+""]):(d&&null!=(e=c.match(/version\/([\.\d]+)/i))&&(d[2]=e[1]),d=d?[d[1],d[2]]:[b,navigator.appVersion,"-?"]);b=d;"undefined"!=typeof b&&null!=b&&1<=b.length&&(c=(b[0]+"").toLowerCase(),b=b[1].split("."),b=parseInt(b[0]),("firefox"==c&&22<=b||"msie"==c&&10<=b||"safari"==c&&5<=b||"chrome"==c)&&_admislocalStorage&&(a=!0));return a},fonts:"",getFont:function(a){ADM_AdsTracking.fonts=a},lcStorage:{timestamp:"timestamp_",get_exprises:function(a,b,c,e){a+="";b=a.indexOf(b,c);c=
a.length-1;return-1!=b?(e=a.indexOf(e,b),-1==e&&(e=c),a.substring(b,e)):""},set_item:function(a,b,c){var e=(new Date).getTime(),d=this.timestamp;e=0==c||""==c?e+63072E7:e+864E5*c;var f="_azs"==a?";":",";c=this.get_exprises(b,d,0,f);b=""==c?b+(d+e.toString()+f):b.replace(c,d+e.toString());localStorage.setItem(a,b)},get_item:function(a,b){var c=localStorage.getItem(a),e=(new Date).getTime(),d=this.timestamp;if(""==c||null==c)return"";endchar="_azs"==a?";":",";var f=this.get_exprises(c,d,0,endchar);
f=f.replace(d,"");return""==f||isNaN(parseInt(f))||parseInt(f)<e?"":c.replace(d+f+endchar,"")},remove_item:function(a){localStorage.removeItem(a)},flush:function(){localStorage.clear()}},setCookie:function(a,b,c,e,d,f){(new Date).getTime();e="/";c=0==c||""==c?(new Date(+new Date+63072E7)).toGMTString():(new Date(+new Date+864E5*c)).toGMTString();a=[a+"="+escape(b)];for(var h in c={expires:c,path:e,domain:d})c[h]&&a.push(h+"="+c[h]);return f&&a.push("secure"),document.cookie=a.join(";"),!0},getCookie:function(a){return 0<
document.cookie.length&&(c_start=document.cookie.indexOf(a+"="),-1!=c_start)?(c_start=c_start+a.length+1,c_end=document.cookie.indexOf(";",c_start),-1==c_end&&(c_end=document.cookie.length),unescape(document.cookie.substring(c_start,c_end))):""},get:function(a){var b="",c="";if("__ui"==a||"__uid"==a||"__create"==a)c=a,a="__uif";if(_admislocalStorage){if("__R"==a||"__RC"==a||"__uif"==a)b=ADM_AdsTracking.getCookie(a);if(null==b||""==b)b=ADM_AdsTracking.lcStorage.get_item(a),null!=b&&""!=b&&ADM_AdsTracking.setCookie(a,
b,"")}else b=ADM_AdsTracking.getCookie(a);if(""!=c&&""!=b){a=b.split("|");for(var e=0,d=a.length;e<d;e++)if(-1!=a[e].indexOf(c+":")){b=a[e].replace(c+":","");break}}return b},set:function(a,b,c){if(_admislocalStorage){if(ADM_AdsTracking.lcStorage.set_item(a,b,c),"__R"==a||"__RC"==a||"__uif"==a)"__R"==a&&"undefined"!=typeof ADS_Location&&ADS_Location!=b&&""!=b&&"0"!=b&&(ADS_Location=parseInt(b)),"__RC"==a&&"undefined"!=typeof ADS_City&&ADS_City!=b&&""!=b&&"0"!=b&&(ADS_City=parseInt(b)),ADM_AdsTracking.setCookie(a,
b,c)}else ADM_AdsTracking.setCookie(a,b,c)},getParam:function(){if(ADM_AdsTracking.checkBrowser()){var a=ADM_AdsTracking.get("__create")+"",b=ADM_AdsTracking.get("__uid")+"";30<b.length&&(b="");""==b&&(a="");11<a.length&&""!=b&&(a=Math.floor((new Date).getTime()/1E3));return"&ce=1&lc="+ADM_AdsTracking.get("__RC")+"&cr="+a+"&ui="+b}return""},getInfoParam:function(){if(ADM_AdsTracking.checkBrowser())return"";var a=ADM_AdsTracking.get("__uid"),b=ADM_AdsTracking.get("__create");return"&ce=1&guie=1&__uid="+
a+"&__create="+b},flashcheck:function(a){for(var b in a)ADM_AdsTracking.check(b,a[b],!0)},expireAllCookies:function(a,b){var c=(new Date(0)).toUTCString();document.cookie=a+"=; expires="+c;for(var e=0,d=b.length;e<d;e++)document.cookie=a+"=; path="+b[e]+"; expires="+c},expireActiveCookies:function(a){for(var b=location.pathname.replace(/\/$/,"").split("/"),c=[],e=0,d=b.length,f;e<d;e++)f=b.slice(0,e+1).join("/"),f=f.replace(/\.([\w]+)/gi,""),""!=f&&(c.push(f),c.push(f+"/"));0<c.length&&ADM_AdsTracking.expireAllCookies(a,
c)},check:function(a,b){switch(a){case "__ui":case "__uid":case "__create":if(2==arguments.length&&"__uid"==a||"__create"==a&&""!=b){ADM_AdsTracking.paramFlash[a]=b;var c=ADM_AdsTracking.getFlashMovie("_admFlck");c&&c.setck&&c.setck(ADM_AdsTracking.paramFlash)}var e=ADM_AdsTracking.get("__uif")+"";if(""==e)e=a+":"+b;else{c=a+":"+b;e=e.split("|");for(var d=[],f=0,h=e.length;f<h;f++)-1==e[f].indexOf(a+":")&&d.push(e[f]);d.push(c);e=d.join("|")}ADM_AdsTracking.set("__uif",e,10);break;default:e=ADM_AdsTracking.get(a),
2==arguments.length&&""!=b&&"0"!=b&&"-1"!=b&&(ADM_AdsTracking.paramFlash[a]=b,(c=ADM_AdsTracking.getFlashMovie("_admFlck"))&&c.setck&&c.setck(ADM_AdsTracking.paramFlash)),e!=b&&ADM_AdsTracking.set(a,b,"")}}};if("undefined"==typeof admaddEventListener)var admaddEventListener$11=function(a,b,c){"addEventListener"in a?a.addEventListener(b,c):"attachEvent"in a&&a.attachEvent("on"+b,c)};if("undefined"==typeof wPrototype)var wPrototype={wdHeight:function(){var a,b=document;"number"==typeof window.innerWidth?
a=window.innerHeight:b.documentElement&&b.documentElement.clientHeight?a=b.documentElement.clientHeight:b.body&&b.body.clientHeight&&(a=b.body.clientHeight);return a},wdWidth:function(){var a,b=document;"number"==typeof window.innerWidth?a=window.innerWidth:b.documentElement&&b.documentElement.clientWidth?a=b.documentElement.clientWidth:b.body&&b.body.clientWidth&&(a=b.body.clientWidth);return a},getElementTop:function(a){var b=document;if(b.getElementById)var c=b.getElementById(a);else b.all&&(c=
b.all[a]);if(null!=c){yPos=c.offsetTop;for(tempEl=c.offsetParent;null!=tempEl;)yPos+=tempEl.offsetTop,tempEl=tempEl.offsetParent;return yPos}return 150},getElementWidth:function(a){return document.getElementById(a).clientWidth},getElementLeft:function(a){var b,c=document;c.getElementById?b=c.getElementById(a):c.all&&(b=c.all[a]);a=b.offsetLeft;for(b=b.offsetParent;null!=b;)a+=b.offsetLeft,b=b.offsetParent;return a},scrollTop:function(){var a=document,b=a.body.scrollTop;0==b&&(b=window.pageYOffset?
window.pageYOffset:a.body.parentElement?a.body.parentElement.scrollTop:0);return b},scrollLeft:function(){var a=document,b=window.pageXOffset?window.pageXOffset:0,c=a.documentElement?a.documentElement.scrollLeft:0;a=a.body?a.body.scrollLeft:0;b=b?b:0;c&&(!b||b>c)&&(b=c);return a&&(!b||b>a)?a:b},bdWidth:function(){var a=document;return bodyWidth=Math.max(Math.max(a.body.scrollWidth,a.documentElement.scrollWidth),Math.max(a.body.offsetWidth,a.documentElement.offsetWidth),Math.max(a.body.clientWidth,
a.documentElement.clientWidth))},bdHeight:function(){var a=document;return Math.max(Math.max(a.body.scrollHeight,a.documentElement.scrollHeight),Math.max(a.body.offsetHeight,a.documentElement.offsetHeight),Math.max(a.body.clientHeight,a.documentElement.clientHeight))}};var _ADMFlashDetect=new function(){var a=this;a.installed=!1;a.raw="";a.major=-1;a.minor=-1;a.revision=-1;a.revisionStr="";var b=[{name:"ShockwaveFlash.ShockwaveFlash.7",version:function(a){return c(a)}},{name:"ShockwaveFlash.ShockwaveFlash.6",
version:function(a){var b="6.0.r21";try{a.AllowScriptAccess="always",b=c(a)}catch(f){}return b}},{name:"ShockwaveFlash.ShockwaveFlash",version:function(a){return c(a)}}],c=function(a){var b=-1;try{b=a.GetVariable("$version")}catch(f){}return b};a.majorAtLeast=function(b){return a.major>=b};a.minorAtLeast=function(b){return a.minor>=b};a.revisionAtLeast=function(b){return a.revision>=b};a.versionAtLeast=function(b){var c=[a.major,a.minor,a.revision],e=Math.min(c.length,arguments.length);for(i=0;i<
e;i++)if(c[i]>=arguments[i]){if(!(i+1<e&&c[i]==arguments[i]))return!0}else return!1};a._ADMFlashDetect=function(){if(navigator.plugins&&0<navigator.plugins.length){var c=navigator.mimeTypes;if(c&&c["application/x-shockwave-flash"]&&c["application/x-shockwave-flash"].enabledPlugin&&c["application/x-shockwave-flash"].enabledPlugin.description){var d=c=c["application/x-shockwave-flash"].enabledPlugin.description;c=d.split(/ +/);var f=c[2].split(/\./);c=c[3];var h=parseInt(f[0],10);var l=parseInt(f[1],
10);var k=c;var m=parseInt(c.replace(/[a-zA-Z]/g,""),10)||a.revision;a.raw=d;a.major=h;a.minor=l;a.revisionStr=k;a.revision=m;a.installed=!0}}else if(-1==navigator.appVersion.indexOf("Mac")&&window.execScript)for(c=-1,f=0;f<b.length&&-1==c;f++){d=-1;try{d=new ActiveXObject(b[f].name)}catch(n){d={activeXError:!0}}d.activeXError||(a.installed=!0,c=b[f].version(d),-1!=c&&(d=c,k=d.split(","),h=parseInt(k[0].split(" ")[1],10),l=parseInt(k[1],10),m=parseInt(k[2],10),k=k[2],a.raw=d.replace("Shockwave Flash ",
""),a.major=h,a.minor=l,a.revision=m,a.revisionStr=k))}}()},paramBrowser={screen_Resolution:screen.width+"x"+screen.height,screen_Color:screen.colorDepth,hostname:document.domain.replace("www.",""),cookieEnabled:navigator.cookieEnabled?1:0,javaEnabled:navigator.javaEnabled()?1:0,referrer:document.referrer,urlLocation:document.URL,url:function(){var a=window.location!=window.parent.location?document.referrer:document.location+"",b=this.hostname;return""==b?a:a.substring(a.indexOf(b)+b.length,a.length)},
flashVersion:function(){return _ADMFlashDetect.major+"."+_ADMFlashDetect.minor+"."+_ADMFlashDetect.revisionStr},zenURL:{encode:function(a){if(-1!=document.domain.indexOf("muachung.vn")&&-1==a.indexOf("http://")){for(var b="undefined"==typeof ADS_CHECKER?"":ADS_CHECKER.getCookie("mc_city"),c="/ha-noi /tp-ho-chi-minh /da-nang /nha-trang /vung-tau /hai-phong".split(" "),e="/Ha-Noi /TP-HCM /Da-Nang /Khanh-Hoa /Ba-Ria-Vung-Tau /Hai-Phong".split(" "),d=0;d<c.length;d++)if(0==a.indexOf(c[d]))return a=a.replace(c[d],
e[d]),encodeURIComponent(a);c={22:"/Ha-Noi",29:"/TP-HCM",15:"/Da-Nang",68:"/Khanh-Hoa",26:"/Hai-Phong",67:"/Ba-Ria-Vung-Tau"};""!=b&&"undefined"!=typeof c[b]&&(a=c[b]+a)}return encodeURIComponent(a)},decode:function(a){return decodeURIComponent(a.replace(/\+/g," "))}}},_ADMBrowser={Version:function(){var a=999;try{var b=navigator.userAgent+"";-1!=navigator.appVersion.indexOf("MSIE")&&(a=parseFloat(navigator.appVersion.split("MSIE")[1]));if(-1!=b.indexOf("Trident")){var c=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/.exec(b);
c&&2<=c.length&&(a=parseFloat(c[1]))}}catch(e){}return a}},_admBrV=_ADMBrowser.Version(),__ADMwdVis=function(){var a,b={hidden:"visibilitychange",webkitHidden:"webkitvisibilitychange",mozHidden:"mozvisibilitychange",msHidden:"msvisibilitychange"};for(a in b)if(a in document){var c=b[a];break}return function(b){b&&document.addEventListener(c,b);return!document[a]}}(),ADM_PPTKSend=ADM_PPTKSend||{};window.admTrackingParam=window.admTrackingParam||{};ADM_PPTKSend.trackingClosePopup=function(){try{paramBrowser.referrer=
paramBrowser.urlLocation,paramBrowser.urlLocation=document.URL,__admPageloadid=window.admTrackingParam.pageloadid,__admloadPageId=window.admTrackingParam.__admloadPageId,__AdmsendRandom=window.admTrackingParam.__AdmsendRandom}catch(a){}try{AdmanlaticPopup.close()}catch(a){}};ADM_PPTKSend.trackingPopup=function(){try{paramBrowser.referrer=paramBrowser.urlLocation,paramBrowser.urlLocation=document.URL,window.admTrackingParam.pageloadid=window.admTrackingParam.pageloadid||__admPageloadid,window.admTrackingParam.__admloadPageId=
window.admTrackingParam.__admloadPageId||__admloadPageId,"undefined"==typeof window.admTrackingParam.__AdmsendRandom&&(window.admTrackingParam.__AdmsendRandom="&lsn="+window.admTrackingParam.pageloadid+ADM_AdsTracking.getParam()),window.admTrackingParam.ispopup=!0,window.__ADM_TrackingSend=!1,window.__admloadPageId=function(){function a(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}return a()+a()+a()+a()+a()+a()+a()+a()}(),__admPageloadid=(new Date).getTime(),window.__AdmsendRandom=
"&lsn="+__admPageloadid+ADM_AdsTracking.getParam(),(new Image).src="//lg1.logging.admicro.vn/ftest?dg="+__admloadPageIdc+ADM_AdsTracking.getParam()+"&url="+encodeURIComponent("http://popup"+document.location.hostname+document.location.pathname)+"&rd="+Math.random(),ADM_TrackingSend$3()}catch(a){}try{AdmanlaticPopup.open()}catch(a){}};ADM_TrackingSend$3();if("undefined"==typeof logposurlviewsend){try{var ptc="https:"==document.location.protocol?"https:":"http:",dmnnews=document.domain;-1==dmnnews.indexOf("googlesyndication")&&
_admloadJs1(ptc+"//static.amcdn.vn/core/lgnews.js")}catch(a){}window.logposurlviewsend="sendnews";AdmonDomReady(function(){try{var a=function(){he=b()+e;if(he>c){c=he;for(var a=[],d=[],k=0;k<f;k++)c>l[k]&&a.push(k);for(k=0;k<a.length;k++){var p=h[k].getAttributeNode("data-check-position").value;d.push(p+":"+l[k])}d=encodeURIComponent(d);logposurlview="&sl="+c+"&si="+d;a.length==f&&("undefined"!=typeof window.__ADMTrackingSendUrl&&""!=window.__ADMTrackingSendUrl&&(img=new Image,img.src=window.__ADMTrackingSendUrl+
logposurlview+"&i="+encodeURIComponent("p;"+__admPageloadid+";"+window.__ADMScrollcounter+";"+window.__ADMScrollEnd+";"+__ADMisActive+";"+__ADMMouse+";"+__ADMTouch+";"+(wPrototype.wdWidth()+"x"+wPrototype.wdHeight())+";"+window.__ifr+";"+("undefined"==typeof ADS_CHECKER?0:1)+";"+__admloadPageId+";"+__admloadPageIdc)+"&rdm="+Math.random()+ADM_AdsTracking.getParam()),chkadmTrackingt||clearTimeout(chkadmTrackingt),chkadmTrackingt=window.setTimeout(function(){ADM_TrackingSendChk()},2E4))}},b=function(){var a=
document.body.scrollTop;0==a&&(a=window.pageYOffset?window.pageYOffset:document.body.parentElement?document.body.parentElement.scrollTop:0);return a},c=0,e=window.innerHeight,d=-1,f=0,h=[];h=document.querySelectorAll("[data-check-position]");f=h.length;for(var l=[],k=0;k<f;k++)l.push(h[k].offsetTop);window.addEventListener("scroll",function(){-1!=d&&clearTimeout(d);d=window.setTimeout(function(){a()},1E3)})}catch(m){}})}}catch(a){(function(){var b=0<document.cookie.length&&(c_start=document.cookie.indexOf("__uif="),
-1!=c_start)?(c_start=c_start+5+1,c_end=document.cookie.indexOf(";",c_start),-1==c_end&&(c_end=document.cookie.length),unescape(document.cookie.substring(c_start,c_end))):"";var c=/__uid:([0-9]+)/.exec(b);b="";c&&2<=c.length&&(b=encodeURIComponent(c[1]));c="https:"==document.location.protocol?"https:":"http:";(new Image).src=c+"//amcdn.vn/blc?lsn="+window.__admloadPageId+"&dg="+window.__admloadPageIdc+"&ui="+b+"&url="+encodeURIComponent("http://error3rdcdn"+document.domain+document.location.pathname)+
"&rd="+Math.random()})()}(function(){if(!window.sendnandatk)try{window.sendnandatk=!0,(new Image).src="//lg.nanda.vn/mapid?src=admicro&dguid="+__admloadPageIdc+"&3guid="+ADM_AdsTracking.get("__uid")}catch(a){}})();